[2025-03-18T20:56:18.713+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T20:56:18.740+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T20:56:18.752+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [queued]>
[2025-03-18T20:56:18.753+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-18T20:56:18.768+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-18 19:18:51.027148+00:00
[2025-03-18T20:56:18.776+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-18T19:18:51.027148+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpe2yozqu_']
[2025-03-18T20:56:18.779+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask silver_ingestion
[2025-03-18T20:56:18.781+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6023) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T20:56:18.782+0000] {standard_task_runner.py:72} INFO - Started process 6024 to run task
[2025-03-18T20:56:18.837+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T19:18:51.027148+00:00 [running]> on host f51d6b911be2
[2025-03-18T20:56:18.931+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T19:18:51.027148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T19:18:51.027148+00:00'
[2025-03-18T20:56:18.932+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T20:56:18.948+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T20:56:18.949+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-18T20:56:18.958+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T20:56:21.720+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SparkContext: Running Spark version 3.5.5
[2025-03-18T20:56:21.722+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T20:56:21.722+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SparkContext: Java version 17.0.14
[2025-03-18T20:56:21.773+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-18T20:56:21.849+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceUtils: ==============================================================
[2025-03-18T20:56:21.850+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-18T20:56:21.850+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceUtils: ==============================================================
[2025-03-18T20:56:21.851+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SparkContext: Submitted application: SilverLayer
[2025-03-18T20:56:21.872+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-18T20:56:21.880+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceProfile: Limiting resource is cpu
[2025-03-18T20:56:21.881+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-18T20:56:21.927+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SecurityManager: Changing view acls to: default
[2025-03-18T20:56:21.928+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SecurityManager: Changing modify acls to: default
[2025-03-18T20:56:21.929+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SecurityManager: Changing view acls groups to:
[2025-03-18T20:56:21.929+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SecurityManager: Changing modify acls groups to:
[2025-03-18T20:56:21.930+0000] {subprocess.py:106} INFO - 25/03/18 20:56:21 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-18T20:56:22.168+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Utils: Successfully started service 'sparkDriver' on port 43961.
[2025-03-18T20:56:22.196+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO SparkEnv: Registering MapOutputTracker
[2025-03-18T20:56:22.229+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-18T20:56:22.247+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-18T20:56:22.248+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-18T20:56:22.252+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-18T20:56:22.275+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2339bd56-a281-4fc0-8ff9-ff048ff3942e
[2025-03-18T20:56:22.293+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-18T20:56:22.312+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-18T20:56:22.465+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-18T20:56:22.554+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-18T20:56:22.718+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Executor: Starting executor ID driver on host f51d6b911be2
[2025-03-18T20:56:22.719+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T20:56:22.720+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Executor: Java version 17.0.14
[2025-03-18T20:56:22.731+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-18T20:56:22.732+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@61f102b2 for default.
[2025-03-18T20:56:22.765+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42883.
[2025-03-18T20:56:22.766+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO NettyBlockTransferService: Server created on f51d6b911be2:42883
[2025-03-18T20:56:22.769+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-18T20:56:22.776+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f51d6b911be2, 42883, None)
[2025-03-18T20:56:22.784+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManagerMasterEndpoint: Registering block manager f51d6b911be2:42883 with 434.4 MiB RAM, BlockManagerId(driver, f51d6b911be2, 42883, None)
[2025-03-18T20:56:22.787+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f51d6b911be2, 42883, None)
[2025-03-18T20:56:22.788+0000] {subprocess.py:106} INFO - 25/03/18 20:56:22 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f51d6b911be2, 42883, None)
[2025-03-18T20:56:23.471+0000] {subprocess.py:106} INFO - 25/03/18 20:56:23 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-18T20:56:23.484+0000] {subprocess.py:106} INFO - 25/03/18 20:56:23 INFO SharedState: Warehouse path is 'file:/tmp/***tmpn3fu9gaw/spark-warehouse'.
[2025-03-18T20:56:24.912+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-18T20:56:24.913+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-18T20:56:24.916+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-18T20:56:24.917+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-18T20:56:24.918+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-18T20:56:24.918+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-18T20:56:24.919+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-18T20:56:24.929+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpn3fu9gaw/bronze_layer.json.
[2025-03-18T20:56:24.993+0000] {subprocess.py:106} INFO - 25/03/18 20:56:24 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-18T20:56:24.994+0000] {subprocess.py:106} INFO - 25/03/18 20:56:24 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-18T20:56:25.008+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO SparkUI: Stopped Spark web UI at http://f51d6b911be2:4040
[2025-03-18T20:56:25.025+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-18T20:56:25.036+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO MemoryStore: MemoryStore cleared
[2025-03-18T20:56:25.037+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO BlockManager: BlockManager stopped
[2025-03-18T20:56:25.043+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-18T20:56:25.047+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-18T20:56:25.056+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO SparkContext: Successfully stopped SparkContext
[2025-03-18T20:56:25.058+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO ShutdownHookManager: Shutdown hook called
[2025-03-18T20:56:25.059+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-93d4cd85-194d-49e1-97fe-7c97e7d8e194
[2025-03-18T20:56:25.064+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-93d4cd85-194d-49e1-97fe-7c97e7d8e194/pyspark-f699f5fd-8d4c-401a-8317-ef600010d399
[2025-03-18T20:56:25.070+0000] {subprocess.py:106} INFO - 25/03/18 20:56:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-d534bb7d-dd2a-474a-9ff4-61e4a9581567
[2025-03-18T20:56:25.105+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-18T20:56:25.118+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T20:56:25.133+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-18T19:18:51.027148+00:00, execution_date=20250318T191851, start_date=20250318T205618, end_date=20250318T205625
[2025-03-18T20:56:25.177+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T20:56:25.178+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 6024)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T20:56:25.215+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T20:56:25.250+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T20:56:25.253+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
