[2025-03-19T16:06:09.570+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T16:06:09.600+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:06:09.614+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:06:09.615+0000] {taskinstance.py:2867} INFO - Starting attempt 14 of 15
[2025-03-19T16:06:09.632+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T16:06:09.640+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp6xr5vcct']
[2025-03-19T16:06:09.645+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask silver_ingestion
[2025-03-19T16:06:09.646+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=358) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T16:06:09.648+0000] {standard_task_runner.py:72} INFO - Started process 359 to run task
[2025-03-19T16:06:09.707+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host bdf158e8d6f0
[2025-03-19T16:06:09.824+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T16:06:09.826+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T16:06:09.843+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T16:06:09.844+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T16:06:09.855+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T16:06:13.936+0000] {subprocess.py:106} INFO - 25/03/19 16:06:13 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T16:06:13.943+0000] {subprocess.py:106} INFO - 25/03/19 16:06:13 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:06:13.944+0000] {subprocess.py:106} INFO - 25/03/19 16:06:13 INFO SparkContext: Java version 17.0.14
[2025-03-19T16:06:14.013+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T16:06:14.126+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceUtils: ==============================================================
[2025-03-19T16:06:14.127+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T16:06:14.128+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceUtils: ==============================================================
[2025-03-19T16:06:14.128+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T16:06:14.160+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T16:06:14.174+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T16:06:14.176+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T16:06:14.239+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SecurityManager: Changing view acls to: default
[2025-03-19T16:06:14.240+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T16:06:14.241+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T16:06:14.242+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T16:06:14.243+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T16:06:14.582+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO Utils: Successfully started service 'sparkDriver' on port 43949.
[2025-03-19T16:06:14.626+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T16:06:14.730+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T16:06:14.778+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T16:06:14.779+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T16:06:14.785+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T16:06:14.820+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-b125044b-f795-4a44-8cc6-07054097de99
[2025-03-19T16:06:14.843+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T16:06:14.861+0000] {subprocess.py:106} INFO - 25/03/19 16:06:14 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T16:06:15.016+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T16:06:15.104+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T16:06:15.257+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Executor: Starting executor ID driver on host bdf158e8d6f0
[2025-03-19T16:06:15.259+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:06:15.259+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Executor: Java version 17.0.14
[2025-03-19T16:06:15.270+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T16:06:15.272+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5b66d90d for default.
[2025-03-19T16:06:15.305+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34249.
[2025-03-19T16:06:15.306+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO NettyBlockTransferService: Server created on bdf158e8d6f0:34249
[2025-03-19T16:06:15.309+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T16:06:15.316+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, bdf158e8d6f0, 34249, None)
[2025-03-19T16:06:15.322+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO BlockManagerMasterEndpoint: Registering block manager bdf158e8d6f0:34249 with 434.4 MiB RAM, BlockManagerId(driver, bdf158e8d6f0, 34249, None)
[2025-03-19T16:06:15.325+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, bdf158e8d6f0, 34249, None)
[2025-03-19T16:06:15.326+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, bdf158e8d6f0, 34249, None)
[2025-03-19T16:06:15.887+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T16:06:15.899+0000] {subprocess.py:106} INFO - 25/03/19 16:06:15 INFO SharedState: Warehouse path is 'file:/tmp/***tmpwf3offco/spark-warehouse'.
[2025-03-19T16:06:17.414+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T16:06:17.415+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T16:06:17.415+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T16:06:17.416+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T16:06:17.417+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T16:06:17.418+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T16:06:17.418+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T16:06:17.430+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpwf3offco/medallion_data/bronze_layer.json.
[2025-03-19T16:06:17.505+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T16:06:17.506+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T16:06:17.522+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO SparkUI: Stopped Spark web UI at http://bdf158e8d6f0:4040
[2025-03-19T16:06:17.541+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T16:06:17.561+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO MemoryStore: MemoryStore cleared
[2025-03-19T16:06:17.563+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO BlockManager: BlockManager stopped
[2025-03-19T16:06:17.570+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T16:06:17.576+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T16:06:17.593+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T16:06:17.594+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T16:06:17.595+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-496d99d7-4c1c-4300-8233-7d5bdbc5380c
[2025-03-19T16:06:17.605+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-496d99d7-4c1c-4300-8233-7d5bdbc5380c/pyspark-255a89ce-7867-49d1-bb97-428769e74231
[2025-03-19T16:06:17.612+0000] {subprocess.py:106} INFO - 25/03/19 16:06:17 INFO ShutdownHookManager: Deleting directory /tmp/spark-3c68d5c2-66a6-4ac8-a2ba-2b85f12acd90
[2025-03-19T16:06:17.654+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T16:06:17.669+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:06:17.681+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T160609, end_date=20250319T160617
[2025-03-19T16:06:17.705+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T16:06:17.707+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T16:06:19.043+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T16:06:19.892+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T16:06:19.894+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 144 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 359)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:06:19.910+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T16:06:19.952+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T16:06:19.954+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
