[2025-03-19T16:01:17.516+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T16:01:17.546+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:01:17.562+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:01:17.563+0000] {taskinstance.py:2867} INFO - Starting attempt 13 of 14
[2025-03-19T16:01:17.592+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T16:01:17.602+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpsr0syvm3']
[2025-03-19T16:01:17.606+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask silver_ingestion
[2025-03-19T16:01:17.609+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=352) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T16:01:17.610+0000] {standard_task_runner.py:72} INFO - Started process 353 to run task
[2025-03-19T16:01:17.675+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 706a24e26271
[2025-03-19T16:01:17.796+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T16:01:17.798+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T16:01:17.816+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T16:01:17.817+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T16:01:17.828+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T16:01:22.179+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T16:01:22.183+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:01:22.184+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SparkContext: Java version 17.0.14
[2025-03-19T16:01:22.259+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T16:01:22.381+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceUtils: ==============================================================
[2025-03-19T16:01:22.382+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T16:01:22.383+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceUtils: ==============================================================
[2025-03-19T16:01:22.384+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T16:01:22.416+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T16:01:22.431+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T16:01:22.432+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T16:01:22.498+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SecurityManager: Changing view acls to: default
[2025-03-19T16:01:22.499+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T16:01:22.500+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T16:01:22.502+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T16:01:22.503+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T16:01:22.900+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO Utils: Successfully started service 'sparkDriver' on port 45739.
[2025-03-19T16:01:22.939+0000] {subprocess.py:106} INFO - 25/03/19 16:01:22 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T16:01:23.000+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T16:01:23.028+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T16:01:23.030+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T16:01:23.036+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T16:01:23.074+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a2084450-eb66-45c0-9ede-e6277a9e3e09
[2025-03-19T16:01:23.099+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T16:01:23.129+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T16:01:23.338+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T16:01:23.419+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T16:01:23.593+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Executor: Starting executor ID driver on host 706a24e26271
[2025-03-19T16:01:23.594+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:01:23.594+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Executor: Java version 17.0.14
[2025-03-19T16:01:23.604+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T16:01:23.605+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@349389c4 for default.
[2025-03-19T16:01:23.635+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41519.
[2025-03-19T16:01:23.636+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO NettyBlockTransferService: Server created on 706a24e26271:41519
[2025-03-19T16:01:23.639+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T16:01:23.646+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 706a24e26271, 41519, None)
[2025-03-19T16:01:23.651+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManagerMasterEndpoint: Registering block manager 706a24e26271:41519 with 434.4 MiB RAM, BlockManagerId(driver, 706a24e26271, 41519, None)
[2025-03-19T16:01:23.656+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 706a24e26271, 41519, None)
[2025-03-19T16:01:23.658+0000] {subprocess.py:106} INFO - 25/03/19 16:01:23 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 706a24e26271, 41519, None)
[2025-03-19T16:01:24.315+0000] {subprocess.py:106} INFO - 25/03/19 16:01:24 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T16:01:24.327+0000] {subprocess.py:106} INFO - 25/03/19 16:01:24 INFO SharedState: Warehouse path is 'file:/tmp/***tmp30u4_9r1/spark-warehouse'.
[2025-03-19T16:01:26.050+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T16:01:26.051+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T16:01:26.052+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T16:01:26.053+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T16:01:26.055+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T16:01:26.056+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T16:01:26.057+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T16:01:26.070+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmp30u4_9r1/medallion_data/bronze_layer.json.
[2025-03-19T16:01:26.150+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T16:01:26.151+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T16:01:26.170+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO SparkUI: Stopped Spark web UI at http://706a24e26271:4040
[2025-03-19T16:01:26.185+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T16:01:26.207+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO MemoryStore: MemoryStore cleared
[2025-03-19T16:01:26.207+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO BlockManager: BlockManager stopped
[2025-03-19T16:01:26.213+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T16:01:26.217+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T16:01:26.239+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T16:01:26.240+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T16:01:26.240+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-fd0d3b04-6e38-4e20-b6ec-1c285acafb2c
[2025-03-19T16:01:26.248+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-fd0d3b04-6e38-4e20-b6ec-1c285acafb2c/pyspark-6f12acdc-4248-437d-b259-4d15677c8d1d
[2025-03-19T16:01:26.256+0000] {subprocess.py:106} INFO - 25/03/19 16:01:26 INFO ShutdownHookManager: Deleting directory /tmp/spark-20d3ed11-0eb0-404c-a417-7c6d0491a4e1
[2025-03-19T16:01:26.294+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T16:01:26.309+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:01:26.319+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T160117, end_date=20250319T160126
[2025-03-19T16:01:26.344+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T16:01:26.344+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T16:01:27.799+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T16:01:28.619+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T16:01:28.619+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 140 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 353)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:01:28.641+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T16:01:28.670+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T16:01:28.673+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
