[2025-03-19T14:17:05.251+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T14:17:05.285+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T14:17:05.303+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T14:17:05.304+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-19T14:17:05.322+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T14:17:05.332+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpgwyxjdhz']
[2025-03-19T14:17:05.335+0000] {standard_task_runner.py:105} INFO - Job 100: Subtask silver_ingestion
[2025-03-19T14:17:05.339+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5940) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T14:17:05.340+0000] {standard_task_runner.py:72} INFO - Started process 5941 to run task
[2025-03-19T14:17:05.397+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 691ef0d21155
[2025-03-19T14:17:05.525+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T14:17:05.527+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T14:17:05.546+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T14:17:05.548+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T14:17:05.558+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T14:17:09.758+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T14:17:09.761+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T14:17:09.762+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO SparkContext: Java version 17.0.14
[2025-03-19T14:17:09.829+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T14:17:09.958+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO ResourceUtils: ==============================================================
[2025-03-19T14:17:09.959+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T14:17:09.963+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO ResourceUtils: ==============================================================
[2025-03-19T14:17:09.964+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T14:17:09.990+0000] {subprocess.py:106} INFO - 25/03/19 14:17:09 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T14:17:10.004+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T14:17:10.006+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T14:17:10.073+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SecurityManager: Changing view acls to: default
[2025-03-19T14:17:10.074+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T14:17:10.075+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T14:17:10.076+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T14:17:10.077+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T14:17:10.471+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO Utils: Successfully started service 'sparkDriver' on port 33165.
[2025-03-19T14:17:10.508+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T14:17:10.574+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T14:17:10.615+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T14:17:10.616+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T14:17:10.625+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T14:17:10.686+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8509ebd9-a56d-4609-b4dc-f6cf81eec646
[2025-03-19T14:17:10.712+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T14:17:10.735+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T14:17:10.888+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T14:17:10.969+0000] {subprocess.py:106} INFO - 25/03/19 14:17:10 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T14:17:11.108+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Executor: Starting executor ID driver on host 691ef0d21155
[2025-03-19T14:17:11.109+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T14:17:11.110+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Executor: Java version 17.0.14
[2025-03-19T14:17:11.120+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T14:17:11.122+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@408dacc5 for default.
[2025-03-19T14:17:11.152+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35801.
[2025-03-19T14:17:11.153+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO NettyBlockTransferService: Server created on 691ef0d21155:35801
[2025-03-19T14:17:11.156+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T14:17:11.165+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 691ef0d21155, 35801, None)
[2025-03-19T14:17:11.172+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO BlockManagerMasterEndpoint: Registering block manager 691ef0d21155:35801 with 434.4 MiB RAM, BlockManagerId(driver, 691ef0d21155, 35801, None)
[2025-03-19T14:17:11.174+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 691ef0d21155, 35801, None)
[2025-03-19T14:17:11.175+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 691ef0d21155, 35801, None)
[2025-03-19T14:17:11.803+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T14:17:11.812+0000] {subprocess.py:106} INFO - 25/03/19 14:17:11 INFO SharedState: Warehouse path is 'file:/tmp/***tmple4u1tr3/spark-warehouse'.
[2025-03-19T14:17:13.416+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T14:17:13.418+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-19T14:17:13.419+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T14:17:13.419+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T14:17:13.420+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T14:17:13.421+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T14:17:13.422+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T14:17:13.437+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmple4u1tr3/medallion_data/bronze_layer.json.
[2025-03-19T14:17:13.516+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T14:17:13.518+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T14:17:13.537+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO SparkUI: Stopped Spark web UI at http://691ef0d21155:4040
[2025-03-19T14:17:13.558+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T14:17:13.576+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO MemoryStore: MemoryStore cleared
[2025-03-19T14:17:13.578+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO BlockManager: BlockManager stopped
[2025-03-19T14:17:13.587+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T14:17:13.594+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T14:17:13.614+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T14:17:13.615+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T14:17:13.617+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-66840766-158e-454a-a192-8f91918a9cd7/pyspark-d54712be-f721-4ec7-829f-5d01dfbecb12
[2025-03-19T14:17:13.626+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-66840766-158e-454a-a192-8f91918a9cd7
[2025-03-19T14:17:13.633+0000] {subprocess.py:106} INFO - 25/03/19 14:17:13 INFO ShutdownHookManager: Deleting directory /tmp/spark-92af38c2-9ed0-46d7-8674-29bfe53b26f1
[2025-03-19T14:17:13.677+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T14:17:13.694+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T14:17:13.711+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T141705, end_date=20250319T141713
[2025-03-19T14:17:13.748+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T14:17:13.749+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T14:17:15.134+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T14:17:15.894+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T14:17:15.896+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 100 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 5941)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T14:17:15.911+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T14:17:15.944+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T14:17:15.946+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
