[2025-03-19T15:49:05.796+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:49:05.885+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:49:05.901+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:49:05.901+0000] {taskinstance.py:2867} INFO - Starting attempt 11 of 12
[2025-03-19T15:49:05.922+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:49:05.930+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpk97dg0ga']
[2025-03-19T15:49:05.934+0000] {standard_task_runner.py:105} INFO - Job 135: Subtask silver_ingestion
[2025-03-19T15:49:05.936+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=497) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:49:05.938+0000] {standard_task_runner.py:72} INFO - Started process 498 to run task
[2025-03-19T15:49:06.042+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 40696cdf9f68
[2025-03-19T15:49:06.484+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:49:06.492+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:49:06.582+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:49:06.588+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:49:06.599+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:49:11.256+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:49:11.259+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:49:11.261+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:49:11.337+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:49:11.451+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceUtils: ==============================================================
[2025-03-19T15:49:11.452+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:49:11.452+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceUtils: ==============================================================
[2025-03-19T15:49:11.453+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:49:11.478+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:49:11.491+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:49:11.493+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:49:11.556+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:49:11.557+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:49:11.558+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:49:11.558+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:49:11.559+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:49:11.874+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO Utils: Successfully started service 'sparkDriver' on port 44651.
[2025-03-19T15:49:11.913+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:49:11.955+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:49:11.979+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:49:11.981+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:49:11.988+0000] {subprocess.py:106} INFO - 25/03/19 15:49:11 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:49:12.016+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-963bd3f9-af6a-4b88-b2dd-5f8a95cbe486
[2025-03-19T15:49:12.035+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:49:12.056+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:49:12.220+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:49:12.311+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:49:12.495+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Executor: Starting executor ID driver on host 40696cdf9f68
[2025-03-19T15:49:12.496+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:49:12.497+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Executor: Java version 17.0.14
[2025-03-19T15:49:12.508+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:49:12.509+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@f4fce95 for default.
[2025-03-19T15:49:12.537+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40821.
[2025-03-19T15:49:12.538+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO NettyBlockTransferService: Server created on 40696cdf9f68:40821
[2025-03-19T15:49:12.540+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:49:12.547+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 40696cdf9f68, 40821, None)
[2025-03-19T15:49:12.552+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO BlockManagerMasterEndpoint: Registering block manager 40696cdf9f68:40821 with 434.4 MiB RAM, BlockManagerId(driver, 40696cdf9f68, 40821, None)
[2025-03-19T15:49:12.555+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 40696cdf9f68, 40821, None)
[2025-03-19T15:49:12.557+0000] {subprocess.py:106} INFO - 25/03/19 15:49:12 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 40696cdf9f68, 40821, None)
[2025-03-19T15:49:13.260+0000] {subprocess.py:106} INFO - 25/03/19 15:49:13 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:49:13.268+0000] {subprocess.py:106} INFO - 25/03/19 15:49:13 INFO SharedState: Warehouse path is 'file:/tmp/***tmp3fcwwzga/spark-warehouse'.
[2025-03-19T15:49:14.872+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:49:14.873+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:49:14.874+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:49:14.874+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:49:14.875+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:49:14.876+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:49:14.877+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:49:14.888+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmp3fcwwzga/medallion_data/bronze_layer.json.
[2025-03-19T15:49:14.976+0000] {subprocess.py:106} INFO - 25/03/19 15:49:14 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:49:14.977+0000] {subprocess.py:106} INFO - 25/03/19 15:49:14 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:49:14.994+0000] {subprocess.py:106} INFO - 25/03/19 15:49:14 INFO SparkUI: Stopped Spark web UI at http://40696cdf9f68:4040
[2025-03-19T15:49:15.013+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:49:15.028+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:49:15.029+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO BlockManager: BlockManager stopped
[2025-03-19T15:49:15.036+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:49:15.040+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:49:15.050+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:49:15.051+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:49:15.051+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-c7ffd49f-b4e5-4aa5-a54c-3eadc397e7df
[2025-03-19T15:49:15.057+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-c7ffd49f-b4e5-4aa5-a54c-3eadc397e7df/pyspark-96254aa3-022a-4e8a-a329-847567239e3f
[2025-03-19T15:49:15.063+0000] {subprocess.py:106} INFO - 25/03/19 15:49:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-0a4afd3d-f6f7-4692-ad26-65f71a32efa7
[2025-03-19T15:49:15.098+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:49:15.113+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:49:15.124+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T154905, end_date=20250319T154915
[2025-03-19T15:49:15.149+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:49:15.149+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:49:16.288+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:49:17.046+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:49:17.047+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 135 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 498)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:49:17.060+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:49:17.090+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:49:17.092+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
