[2025-03-19T15:44:49.274+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:44:49.302+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:44:49.316+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:44:49.317+0000] {taskinstance.py:2867} INFO - Starting attempt 9 of 10
[2025-03-19T15:44:49.334+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:44:49.343+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpz9pjdjen']
[2025-03-19T15:44:49.346+0000] {standard_task_runner.py:105} INFO - Job 130: Subtask silver_ingestion
[2025-03-19T15:44:49.348+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:44:49.349+0000] {standard_task_runner.py:72} INFO - Started process 351 to run task
[2025-03-19T15:44:49.412+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 95caac6b62ba
[2025-03-19T15:44:49.529+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:44:49.530+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:44:49.550+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:44:49.551+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:44:49.561+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:44:53.989+0000] {subprocess.py:106} INFO - 25/03/19 15:44:53 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:44:53.992+0000] {subprocess.py:106} INFO - 25/03/19 15:44:53 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:44:53.993+0000] {subprocess.py:106} INFO - 25/03/19 15:44:53 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:44:54.073+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:44:54.201+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceUtils: ==============================================================
[2025-03-19T15:44:54.202+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:44:54.203+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceUtils: ==============================================================
[2025-03-19T15:44:54.203+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:44:54.235+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:44:54.246+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:44:54.247+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:44:54.306+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:44:54.306+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:44:54.307+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:44:54.308+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:44:54.308+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:44:54.621+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO Utils: Successfully started service 'sparkDriver' on port 46071.
[2025-03-19T15:44:54.665+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:44:54.709+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:44:54.730+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:44:54.731+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:44:54.738+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:44:54.761+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-16734076-6e49-4665-983a-db5ada53aaa8
[2025-03-19T15:44:54.778+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:44:54.801+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:44:54.993+0000] {subprocess.py:106} INFO - 25/03/19 15:44:54 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:44:55.098+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:44:55.242+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Executor: Starting executor ID driver on host 95caac6b62ba
[2025-03-19T15:44:55.243+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:44:55.243+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Executor: Java version 17.0.14
[2025-03-19T15:44:55.255+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:44:55.256+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6710369a for default.
[2025-03-19T15:44:55.281+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39847.
[2025-03-19T15:44:55.282+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO NettyBlockTransferService: Server created on 95caac6b62ba:39847
[2025-03-19T15:44:55.285+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:44:55.293+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 95caac6b62ba, 39847, None)
[2025-03-19T15:44:55.297+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO BlockManagerMasterEndpoint: Registering block manager 95caac6b62ba:39847 with 434.4 MiB RAM, BlockManagerId(driver, 95caac6b62ba, 39847, None)
[2025-03-19T15:44:55.300+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 95caac6b62ba, 39847, None)
[2025-03-19T15:44:55.301+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 95caac6b62ba, 39847, None)
[2025-03-19T15:44:55.924+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:44:55.938+0000] {subprocess.py:106} INFO - 25/03/19 15:44:55 INFO SharedState: Warehouse path is 'file:/tmp/***tmpnbdx41tp/spark-warehouse'.
[2025-03-19T15:44:57.449+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:44:57.449+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:44:57.450+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:44:57.451+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:44:57.451+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:44:57.452+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:44:57.453+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:44:57.463+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpnbdx41tp/medallion_data/bronze_layer.json.
[2025-03-19T15:44:57.540+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:44:57.541+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:44:57.557+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO SparkUI: Stopped Spark web UI at http://95caac6b62ba:4040
[2025-03-19T15:44:57.573+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:44:57.587+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:44:57.588+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO BlockManager: BlockManager stopped
[2025-03-19T15:44:57.594+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:44:57.597+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:44:57.608+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:44:57.609+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:44:57.609+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-96fb4f91-d713-4e80-81c9-3f89a601c837/pyspark-6eccb980-617c-4659-84d2-1e2d7d901f36
[2025-03-19T15:44:57.616+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-96fb4f91-d713-4e80-81c9-3f89a601c837
[2025-03-19T15:44:57.626+0000] {subprocess.py:106} INFO - 25/03/19 15:44:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-90a2a55c-0710-4e32-b878-d0f296aaca6d
[2025-03-19T15:44:57.661+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:44:57.675+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:44:57.686+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T154449, end_date=20250319T154457
[2025-03-19T15:44:57.708+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:44:57.709+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:44:59.039+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:44:59.871+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:44:59.872+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 130 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 351)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:44:59.900+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:44:59.941+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:44:59.944+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
