[2025-03-19T15:48:30.491+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:48:30.521+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:48:30.536+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:48:30.537+0000] {taskinstance.py:2867} INFO - Starting attempt 10 of 11
[2025-03-19T15:48:30.555+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:48:30.564+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpctaik0d5']
[2025-03-19T15:48:30.567+0000] {standard_task_runner.py:105} INFO - Job 133: Subtask silver_ingestion
[2025-03-19T15:48:30.569+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=219) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:48:30.570+0000] {standard_task_runner.py:72} INFO - Started process 220 to run task
[2025-03-19T15:48:30.624+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 40696cdf9f68
[2025-03-19T15:48:30.752+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:48:30.754+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:48:30.795+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:48:30.796+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:48:30.809+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:48:35.138+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:48:35.142+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:48:35.143+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:48:35.230+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:48:35.362+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceUtils: ==============================================================
[2025-03-19T15:48:35.362+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:48:35.363+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceUtils: ==============================================================
[2025-03-19T15:48:35.364+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:48:35.389+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:48:35.401+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:48:35.403+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:48:35.467+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:48:35.468+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:48:35.468+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:48:35.469+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:48:35.470+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:48:35.865+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO Utils: Successfully started service 'sparkDriver' on port 34405.
[2025-03-19T15:48:35.904+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:48:35.944+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:48:35.967+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:48:35.970+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:48:35.977+0000] {subprocess.py:106} INFO - 25/03/19 15:48:35 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:48:36.003+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a51eab6b-bc0e-4d78-b2c6-6f5ae193ef1d
[2025-03-19T15:48:36.027+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:48:36.047+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:48:36.209+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:48:36.331+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:48:36.649+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Executor: Starting executor ID driver on host 40696cdf9f68
[2025-03-19T15:48:36.649+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:48:36.650+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Executor: Java version 17.0.14
[2025-03-19T15:48:36.660+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:48:36.662+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@f4fce95 for default.
[2025-03-19T15:48:36.693+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38323.
[2025-03-19T15:48:36.694+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO NettyBlockTransferService: Server created on 40696cdf9f68:38323
[2025-03-19T15:48:36.696+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:48:36.707+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 40696cdf9f68, 38323, None)
[2025-03-19T15:48:36.711+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO BlockManagerMasterEndpoint: Registering block manager 40696cdf9f68:38323 with 434.4 MiB RAM, BlockManagerId(driver, 40696cdf9f68, 38323, None)
[2025-03-19T15:48:36.715+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 40696cdf9f68, 38323, None)
[2025-03-19T15:48:36.717+0000] {subprocess.py:106} INFO - 25/03/19 15:48:36 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 40696cdf9f68, 38323, None)
[2025-03-19T15:48:37.331+0000] {subprocess.py:106} INFO - 25/03/19 15:48:37 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:48:37.342+0000] {subprocess.py:106} INFO - 25/03/19 15:48:37 INFO SharedState: Warehouse path is 'file:/tmp/***tmp8y4m4cp4/spark-warehouse'.
[2025-03-19T15:48:38.932+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:48:38.932+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:48:38.933+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:48:38.936+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:48:38.936+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:48:38.937+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:48:38.938+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:48:38.947+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmp8y4m4cp4/medallion_data/bronze_layer.json.
[2025-03-19T15:48:39.028+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:48:39.029+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:48:39.047+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO SparkUI: Stopped Spark web UI at http://40696cdf9f68:4040
[2025-03-19T15:48:39.061+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:48:39.075+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:48:39.076+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO BlockManager: BlockManager stopped
[2025-03-19T15:48:39.083+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:48:39.086+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:48:39.099+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:48:39.100+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:48:39.102+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-e59d7cd6-45a5-418f-85af-029076d3755b/pyspark-52cf6e83-9d28-4685-a0eb-9ccc5c87a81b
[2025-03-19T15:48:39.108+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-e59d7cd6-45a5-418f-85af-029076d3755b
[2025-03-19T15:48:39.117+0000] {subprocess.py:106} INFO - 25/03/19 15:48:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-0c3aa46e-d8a2-4355-ae73-81e80a904181
[2025-03-19T15:48:39.151+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:48:39.164+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:48:39.177+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T154830, end_date=20250319T154839
[2025-03-19T15:48:39.200+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:48:39.201+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:48:40.553+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:48:41.316+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:48:41.317+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 133 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 220)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:48:41.352+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:48:41.380+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:48:41.382+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
