[2025-03-19T15:01:06.175+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:01:06.203+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:01:06.217+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:01:06.217+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-03-19T15:01:06.235+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:01:06.244+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpkvhckuio']
[2025-03-19T15:01:06.249+0000] {standard_task_runner.py:105} INFO - Job 111: Subtask silver_ingestion
[2025-03-19T15:01:06.250+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=473) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:01:06.251+0000] {standard_task_runner.py:72} INFO - Started process 474 to run task
[2025-03-19T15:01:06.324+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host ef5eed66b5b5
[2025-03-19T15:01:06.438+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:01:06.439+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:01:06.457+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:01:06.459+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:01:06.468+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:01:11.459+0000] {subprocess.py:106} INFO - 25/03/19 15:01:11 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:01:11.469+0000] {subprocess.py:106} INFO - 25/03/19 15:01:11 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:01:11.471+0000] {subprocess.py:106} INFO - 25/03/19 15:01:11 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:01:11.746+0000] {subprocess.py:106} INFO - 25/03/19 15:01:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:01:12.075+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceUtils: ==============================================================
[2025-03-19T15:01:12.077+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:01:12.080+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceUtils: ==============================================================
[2025-03-19T15:01:12.082+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:01:12.155+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:01:12.188+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:01:12.191+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:01:12.350+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:01:12.352+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:01:12.354+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:01:12.355+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:01:12.357+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:01:12.972+0000] {subprocess.py:106} INFO - 25/03/19 15:01:12 INFO Utils: Successfully started service 'sparkDriver' on port 46543.
[2025-03-19T15:01:13.011+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:01:13.074+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:01:13.152+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:01:13.154+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:01:13.162+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:01:13.271+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c270b19b-8f06-4a54-a9c8-db477f2f238b
[2025-03-19T15:01:13.329+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:01:13.381+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:01:13.805+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:01:13.983+0000] {subprocess.py:106} INFO - 25/03/19 15:01:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:01:14.265+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Executor: Starting executor ID driver on host ef5eed66b5b5
[2025-03-19T15:01:14.267+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:01:14.268+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Executor: Java version 17.0.14
[2025-03-19T15:01:14.303+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:01:14.319+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5123949a for default.
[2025-03-19T15:01:14.477+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36977.
[2025-03-19T15:01:14.478+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO NettyBlockTransferService: Server created on ef5eed66b5b5:36977
[2025-03-19T15:01:14.484+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:01:14.513+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, ef5eed66b5b5, 36977, None)
[2025-03-19T15:01:14.521+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO BlockManagerMasterEndpoint: Registering block manager ef5eed66b5b5:36977 with 434.4 MiB RAM, BlockManagerId(driver, ef5eed66b5b5, 36977, None)
[2025-03-19T15:01:14.529+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, ef5eed66b5b5, 36977, None)
[2025-03-19T15:01:14.532+0000] {subprocess.py:106} INFO - 25/03/19 15:01:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, ef5eed66b5b5, 36977, None)
[2025-03-19T15:01:16.076+0000] {subprocess.py:106} INFO - 25/03/19 15:01:16 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:01:16.101+0000] {subprocess.py:106} INFO - 25/03/19 15:01:16 INFO SharedState: Warehouse path is 'file:/tmp/***tmphakpabtw/spark-warehouse'.
[2025-03-19T15:01:18.707+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:01:18.707+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-19T15:01:18.709+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:01:18.710+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:01:18.711+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:01:18.714+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:01:18.716+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:01:18.729+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmphakpabtw/medallion_data/bronze_layer.json.
[2025-03-19T15:01:18.829+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:01:18.830+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:01:18.849+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO SparkUI: Stopped Spark web UI at http://ef5eed66b5b5:4040
[2025-03-19T15:01:18.872+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:01:18.899+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:01:18.900+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO BlockManager: BlockManager stopped
[2025-03-19T15:01:18.910+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:01:18.916+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:01:18.929+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:01:18.930+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:01:18.930+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-44b6a990-8c28-48fb-9305-a0257fb40b70
[2025-03-19T15:01:18.939+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-295dfb4d-4c1c-4c1c-a901-79a3b7ee66dc/pyspark-491e05aa-cd89-4442-8a5a-102376efc0f1
[2025-03-19T15:01:18.947+0000] {subprocess.py:106} INFO - 25/03/19 15:01:18 INFO ShutdownHookManager: Deleting directory /tmp/spark-295dfb4d-4c1c-4c1c-a901-79a3b7ee66dc
[2025-03-19T15:01:19.005+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:01:19.032+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:01:19.047+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T150106, end_date=20250319T150119
[2025-03-19T15:01:19.085+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:01:19.086+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:01:20.506+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:01:21.341+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:01:21.342+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 111 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 474)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:01:21.374+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:01:21.407+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:01:21.410+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
