[2025-03-18T20:56:30.009+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T20:56:30.035+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [queued]>
[2025-03-18T20:56:30.048+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [queued]>
[2025-03-18T20:56:30.049+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-18T20:56:30.066+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-18 20:56:22.390623+00:00
[2025-03-18T20:56:30.073+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-18T20:56:22.390623+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpyrum_zd_']
[2025-03-18T20:56:30.077+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask silver_ingestion
[2025-03-18T20:56:30.078+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6304) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T20:56:30.080+0000] {standard_task_runner.py:72} INFO - Started process 6305 to run task
[2025-03-18T20:56:30.134+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-18T20:56:22.390623+00:00 [running]> on host f51d6b911be2
[2025-03-18T20:56:30.239+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T20:56:22.390623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-18T20:56:22.390623+00:00'
[2025-03-18T20:56:30.240+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T20:56:30.256+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-18T20:56:30.257+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-18T20:56:30.266+0000] {subprocess.py:99} INFO - Output:
[2025-03-18T20:56:33.002+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkContext: Running Spark version 3.5.5
[2025-03-18T20:56:33.004+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T20:56:33.005+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkContext: Java version 17.0.14
[2025-03-18T20:56:33.056+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-18T20:56:33.141+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceUtils: ==============================================================
[2025-03-18T20:56:33.141+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-18T20:56:33.142+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceUtils: ==============================================================
[2025-03-18T20:56:33.143+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkContext: Submitted application: SilverLayer
[2025-03-18T20:56:33.163+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-18T20:56:33.172+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceProfile: Limiting resource is cpu
[2025-03-18T20:56:33.173+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-18T20:56:33.219+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SecurityManager: Changing view acls to: default
[2025-03-18T20:56:33.219+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SecurityManager: Changing modify acls to: default
[2025-03-18T20:56:33.220+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SecurityManager: Changing view acls groups to:
[2025-03-18T20:56:33.221+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SecurityManager: Changing modify acls groups to:
[2025-03-18T20:56:33.221+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-18T20:56:33.505+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Utils: Successfully started service 'sparkDriver' on port 34425.
[2025-03-18T20:56:33.533+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkEnv: Registering MapOutputTracker
[2025-03-18T20:56:33.566+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-18T20:56:33.586+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-18T20:56:33.587+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-18T20:56:33.591+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-18T20:56:33.612+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-cee03d5b-de92-4344-95dd-8f40d6ca6bcf
[2025-03-18T20:56:33.625+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-18T20:56:33.640+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-18T20:56:33.765+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-18T20:56:33.826+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-18T20:56:33.941+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Executor: Starting executor ID driver on host f51d6b911be2
[2025-03-18T20:56:33.942+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-18T20:56:33.942+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Executor: Java version 17.0.14
[2025-03-18T20:56:33.950+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-18T20:56:33.950+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@750fe89c for default.
[2025-03-18T20:56:33.971+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40597.
[2025-03-18T20:56:33.972+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO NettyBlockTransferService: Server created on f51d6b911be2:40597
[2025-03-18T20:56:33.973+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-18T20:56:33.979+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f51d6b911be2, 40597, None)
[2025-03-18T20:56:33.983+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManagerMasterEndpoint: Registering block manager f51d6b911be2:40597 with 434.4 MiB RAM, BlockManagerId(driver, f51d6b911be2, 40597, None)
[2025-03-18T20:56:33.985+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f51d6b911be2, 40597, None)
[2025-03-18T20:56:33.986+0000] {subprocess.py:106} INFO - 25/03/18 20:56:33 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f51d6b911be2, 40597, None)
[2025-03-18T20:56:34.424+0000] {subprocess.py:106} INFO - 25/03/18 20:56:34 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-18T20:56:34.431+0000] {subprocess.py:106} INFO - 25/03/18 20:56:34 INFO SharedState: Warehouse path is 'file:/tmp/***tmps_1x8mc8/spark-warehouse'.
[2025-03-18T20:56:35.622+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-18T20:56:35.623+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-18T20:56:35.623+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-18T20:56:35.624+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-18T20:56:35.624+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-18T20:56:35.625+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-18T20:56:35.625+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-18T20:56:35.634+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmps_1x8mc8/bronze_layer.json.
[2025-03-18T20:56:35.680+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-18T20:56:35.681+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-18T20:56:35.695+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO SparkUI: Stopped Spark web UI at http://f51d6b911be2:4040
[2025-03-18T20:56:35.709+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-18T20:56:35.721+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO MemoryStore: MemoryStore cleared
[2025-03-18T20:56:35.724+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO BlockManager: BlockManager stopped
[2025-03-18T20:56:35.727+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-18T20:56:35.731+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-18T20:56:35.739+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO SparkContext: Successfully stopped SparkContext
[2025-03-18T20:56:35.740+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO ShutdownHookManager: Shutdown hook called
[2025-03-18T20:56:35.740+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-7bc1949b-3109-45de-a76a-744b1622069a
[2025-03-18T20:56:35.746+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-7bc1949b-3109-45de-a76a-744b1622069a/pyspark-74d612ea-1017-4971-b492-0978a2319ddd
[2025-03-18T20:56:35.752+0000] {subprocess.py:106} INFO - 25/03/18 20:56:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-6acad6eb-f9e4-4669-b274-f61d7c8c0a9e
[2025-03-18T20:56:35.795+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-18T20:56:35.811+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T20:56:35.823+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-18T20:56:22.390623+00:00, execution_date=20250318T205622, start_date=20250318T205630, end_date=20250318T205635
[2025-03-18T20:56:35.868+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T20:56:35.869+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 6305)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-18T20:56:35.902+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-18T20:56:35.931+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-18T20:56:35.933+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
